import Head from 'next/head'
import { FaFacebookF, FaLinkedin, FaGoogle, FaRegEnvelope } from 'react-icons/fa'
import { MdLockOutline } from 'react-icons/md'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center min-h-screen w-full flex-1 px-20 text-center bg-gray-100">
        <div className="bg-white rounded-2xl shadow-lg flex w-2/3 max-w-4xl">
          <div className='w-3/5 p-5'>
            <div className="text-left font-bold text-2xl">
              <a href="#"><span className='text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-blue-500'>Nuxt</span>Web</a>
            </div>
            <div className='py-10'>

              <h2 className='text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-blue-500 mb-2'>Sign in to Account</h2>

              <div className='border-2 w-10 border-cyan-500 mb-2 inline-block'></div>

              <div className='flex justify-center my-2'>
                <a href="#" className='border-2 border-gray-200 rounded-full p-3 mx-1'><FaFacebookF className='text-sm'/></a>

                <a href="#" className='border-2 border-gray-200 rounded-full p-3 mx-1'><FaLinkedin className='text-sm'/></a>

                <a href="#" className='border-2 border-gray-200 rounded-full p-3 mx-1'><FaGoogle className='text-sm'/></a>
              </div>

              <p className='text-gray-400 text-[15px] my-3'>Or use your email account</p>

              <div className="flex flex-col items-center">
                <div className='bg-gray-100 w-64 p-2 flex items-center mb-2'>
                  <FaRegEnvelope className='text-gray-400 m-2'/>
                  <input type="email" name='email' placeholder='Email ' className='bg-transparent outline-none text-sm flex-1' />
                </div>

                <div className='bg-gray-100 w-64 p-2 flex items-center mb-3'>
                  <MdLockOutline  className='text-gray-400 m-2'/>
                  <input type="password" name='password' placeholder='Password ' className='bg-transparent outline-none text-sm flex-1' />
                </div>

                <div className="flex justify-between w-64 mb-5">
                  <label className='flex items-center text-xs hover:text-cyan-500 cursor-pointer'>
                    <input type="checkbox" name='remember' className='mr-1 '/> Remember me
                  </label>
                  <a href="#" className='text-xs hover:text-cyan-500'>Forgot Password?</a>
                </div>

                <a href="#" className='bg-gradient-to-r from-cyan-500 to-blue-500 text-white  rounded-full px-12 py-3 inline-block font-semibold'>Sign In</a>
              </div>

            </div>
          </div>

          <div className='w-2/5 bg-gradient-to-r from-cyan-500 to-blue-500 text-white rounded-tr-2xl rounded-br-2xl py-36 px-12'>

            <h2 className='text-3xl font-bold mb-2'>Hello, Friend!</h2>

            <div className='border-2 w-10 border-white mb-2 inline-block'></div>

            <p className='mb-10'>Fill up personal information and start journey with us.</p>
            <a href="#" className='border-2 border-white rounded-full px-12 py-2 inline-block font-semibold hover:bg-white hover:text-cyan-500'>Sign Up</a>

          </div>
        </div>
      </main>
    </>
  )
}
